# Generated by Django 5.1.1 on 2024-10-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_quotarequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quota_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
