# Generated by Django 5.1.1 on 2024-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_course_quota_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject_amount_remaining',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
