# Generated by Django 5.1.1 on 2024-10-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_subject_amount_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject_credit',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
